import type { MotionPreset } from '@/types/motion';

/**
 * The built-in Motion Background Library catalog — 54 original presets
 * across six collections (Worship, Prayer, Bible, Sermon, Countdown,
 * Announcement). Every preset is a named, fully-documented parameterization
 * of one of the eight generator engines in `motionEngines.ts` (see that
 * file's header for why that's the right architecture, not a shortcut).
 *
 * This is static, bundled catalog data — not a database table. It ships
 * with the app like `editorConstants.ts`'s COLOR_SWATCHES; the only thing
 * that's actually per-user and persisted is which ids are favorited
 * (`motion_favorites` table, see supabase/migrations and useMotionFavorites).
 */
export const MOTION_PRESETS: MotionPreset[] = [
  // ───────────────────────────── Worship ─────────────────────────────
  {
    id: 'worship-golden-hour-bokeh',
    name: 'Golden Hour Bokeh',
    category: 'worship',
    description: 'Warm, glowing bokeh orbs drifting upward through a deep amber haze — the visual feeling of a sunset worship set.',
    visualBehavior: 'Soft glowing dots of varying size rise slowly from the bottom of the frame, gently swaying side to side, fading in size-based glow.',
    animationSpec: 'particles engine · 46 particles · up direction · speed 14px/s · glow+twinkle on · amber/gold palette over a near-black base.',
    thumbnailConcept: 'A dark warm-brown tile scattered with soft glowing amber circles of different sizes, brighter near the bottom.',
    tags: ['warm', 'gold', 'bokeh', 'worship', 'sunset', 'glow'],
    recommendedUsage: 'Opening worship songs, slow bridges, altar-call moments needing warmth without distraction.',
    params: { engine: 'particles', background: '#160f08', particleColors: ['#f2b84b', '#e8983a', '#fdd98b'], count: 46, minSize: 2, maxSize: 7, direction: 'up', speed: 14, glow: true, twinkle: true },
  },
  {
    id: 'worship-ocean-horizon-waves',
    name: 'Ocean Horizon Waves',
    category: 'worship',
    description: 'Layered deep-blue wave bands roll slowly across the lower frame, like a calm sea beneath a night sky.',
    visualBehavior: 'Three translucent horizontal wave bands undulate at slightly different speeds and depths, creating gentle parallax.',
    animationSpec: 'waves engine · 3 layers · amplitude 22px · speed 6 · gradient fill · teal/blue palette.',
    thumbnailConcept: 'Dark navy tile with three soft overlapping wave silhouettes near the bottom third.',
    tags: ['blue', 'ocean', 'calm', 'worship', 'waves'],
    recommendedUsage: 'Reflective worship songs referencing water, peace, or stillness ("Oceans", "Still").',
    params: { engine: 'waves', background: '#050b14', bandColors: ['#0e3a52', '#146b82', '#1f95a3'], layers: 3, amplitude: 22, speed: 6, fill: 'gradient' },
  },
  {
    id: 'worship-northern-light-aurora',
    name: 'Northern Light Aurora',
    category: 'worship',
    description: 'Soft ribbons of teal, violet, and rose drift and blur across a midnight sky, like the aurora borealis.',
    visualBehavior: 'Wide blurred color ribbons slowly rise and fall in overlapping waves, blending where they cross.',
    animationSpec: 'aurora engine · 4 ribbons · blur 40px · speed 5 · teal/violet/rose palette on near-black base.',
    thumbnailConcept: 'A near-black tile with soft overlapping blurred bands of teal and violet light.',
    tags: ['aurora', 'worship', 'ribbons', 'night', 'atmospheric'],
    recommendedUsage: 'Awe/wonder-themed worship, Christmas or Easter worship sets, big emotional builds.',
    params: { engine: 'aurora', background: '#04060d', ribbonColors: ['#2fb8a6', '#7a5cd6', '#d1608f'], ribbons: 4, speed: 5, blurPx: 40 },
  },
  {
    id: 'worship-rising-embers',
    name: 'Rising Embers',
    category: 'worship',
    description: 'Small glowing ember-red particles float upward against a near-black backdrop, like sparks from a fire.',
    visualBehavior: 'Small bright dots rise steadily with a slight side-to-side flicker, thinning out near the top of the frame.',
    animationSpec: 'particles engine · 60 particles · up direction · speed 22px/s · glow+twinkle on · ember red/orange palette.',
    thumbnailConcept: 'Black tile with small bright red-orange glowing sparks concentrated toward the bottom.',
    tags: ['embers', 'fire', 'red', 'worship', 'passion'],
    recommendedUsage: 'High-energy worship, songs about fire/refining/passion, revival-themed services.',
    params: { engine: 'particles', background: '#0a0402', particleColors: ['#e3401f', '#f2632a', '#ffb066'], count: 60, minSize: 1, maxSize: 4, direction: 'up', speed: 22, glow: true, twinkle: true },
  },
  {
    id: 'worship-violet-dawn-gradient',
    name: 'Violet Dawn Gradient',
    category: 'worship',
    description: 'A slow-shifting diagonal gradient moving through violet, rose, and burnt orange — like dawn breaking.',
    visualBehavior: 'The whole frame\'s color gently drifts back and forth between the palette over roughly a minute.',
    animationSpec: 'gradient-drift engine · angle 35° · speed 1.4 cycles/min · grain on · violet/rose/orange palette.',
    thumbnailConcept: 'A diagonal gradient swatch moving from deep violet at one corner to warm orange at the other.',
    tags: ['gradient', 'dawn', 'violet', 'worship', 'soft'],
    recommendedUsage: 'General-purpose worship background when lyrics need a calm, color-rich, non-busy backdrop.',
    params: { engine: 'gradient-drift', colors: ['#3a1f4d', '#7a3a5e', '#c2703a'], angleDeg: 35, speed: 1.4, grain: true },
  },
  {
    id: 'worship-starlight-drift',
    name: 'Starlight Drift',
    category: 'worship',
    description: 'Tiny white and pale-blue points twinkle and drift slowly across a deep space-blue backdrop.',
    visualBehavior: 'Small dots gently drift in loose orbits, twinkling in brightness independently of one another.',
    animationSpec: 'particles engine · 90 particles · drift direction · speed 4px/s · twinkle on, glow off · white/pale-blue palette.',
    thumbnailConcept: 'A deep navy tile scattered evenly with tiny white and pale blue dots, like a starfield.',
    tags: ['stars', 'night', 'blue', 'worship', 'twinkle'],
    recommendedUsage: 'Christmas Eve services, songs about God\'s vastness/creation, quiet worship openers.',
    params: { engine: 'particles', background: '#050814', particleColors: ['#ffffff', '#bcd4ff', '#8fb2ff'], count: 90, minSize: 1, maxSize: 2.5, direction: 'drift', speed: 4, glow: false, twinkle: true },
  },
  {
    id: 'worship-emerald-rays',
    name: 'Emerald Rays',
    category: 'worship',
    description: 'Soft green light rays sweep slowly outward from above, like sunlight through a forest canopy.',
    visualBehavior: 'Faint triangular rays rotate very slowly around a point above the frame, brightening and dimming as they overlap.',
    animationSpec: 'rays engine · 10 rays · origin top · speed 2°/min · opacity 0.35 · emerald green palette.',
    thumbnailConcept: 'A dark green tile with faint lighter-green ray shapes fanning down from the top edge.',
    tags: ['green', 'rays', 'worship', 'light', 'growth'],
    recommendedUsage: 'Songs about growth, new life, or God\'s provision; general worship background with a nature feel.',
    params: { engine: 'rays', background: '#04140d', rayColor: '#3ecb8f', rayCount: 10, speed: 2, origin: 'top', opacity: 0.35 },
  },
  {
    id: 'worship-crimson-tide-waves',
    name: 'Crimson Tide Waves',
    category: 'worship',
    description: 'Deep red and maroon wave bands move slowly across the lower frame — bold, warm, and reverent.',
    visualBehavior: 'Two wide wave bands rise and fall with a slow, heavy rhythm, like a slow-motion tide.',
    animationSpec: 'waves engine · 2 layers · amplitude 28px · speed 4 · solid fill · deep red/maroon palette.',
    thumbnailConcept: 'A near-black tile with two overlapping deep-red wave shapes near the bottom.',
    tags: ['red', 'worship', 'bold', 'waves', 'reverent'],
    recommendedUsage: 'Communion services, songs about the cross/sacrifice, solemn worship moments.',
    params: { engine: 'waves', background: '#0d0505', bandColors: ['#5c1414', '#8a2020'], layers: 2, amplitude: 28, speed: 4, fill: 'solid' },
  },
  {
    id: 'worship-amber-grid-pulse',
    name: 'Amber Grid Pulse',
    category: 'worship',
    description: 'A faint amber grid slowly drifts and pulses in brightness, giving a modern-worship, concert-lighting feel.',
    visualBehavior: 'Thin grid lines drift diagonally at a steady pace while their overall brightness pulses slowly in and out.',
    animationSpec: 'geometric engine · grid shape · density 6 · speed 1.5 · pulse on · amber lines on near-black base.',
    thumbnailConcept: 'A dark tile with a faint amber grid pattern, brighter at the intersections.',
    tags: ['grid', 'modern', 'amber', 'worship', 'concert'],
    recommendedUsage: 'Modern/contemporary worship sets with a concert-lighting aesthetic; up-tempo songs.',
    params: { engine: 'geometric', background: '#100b04', lineColor: '#e0a13d', shape: 'grid', density: 6, speed: 1.5, pulse: true },
  },

  // ───────────────────────────── Prayer ─────────────────────────────
  {
    id: 'prayer-quiet-candlelight',
    name: 'Quiet Candlelight',
    category: 'prayer',
    description: 'A handful of dim, warm glowing dots drift almost imperceptibly, like distant candles in a still room.',
    visualBehavior: 'Very few soft orange dots hover and drift extremely slowly, barely moving frame to frame.',
    animationSpec: 'particles engine · 14 particles · drift direction · speed 2px/s · glow on, no twinkle · warm amber palette.',
    thumbnailConcept: 'A near-black tile with a few very soft, dim orange glows scattered sparsely.',
    tags: ['prayer', 'candle', 'still', 'warm', 'quiet'],
    recommendedUsage: 'Corporate prayer, altar ministry time, moments of silence.',
    params: { engine: 'particles', background: '#0b0705', particleColors: ['#c47a2e', '#e0964a'], count: 14, minSize: 3, maxSize: 6, direction: 'drift', speed: 2, glow: true, twinkle: false },
  },
  {
    id: 'prayer-still-waters',
    name: 'Still Waters',
    category: 'prayer',
    description: 'A single, barely-moving wave band in muted blue-gray — stillness rendered as motion.',
    visualBehavior: 'One wide, low-amplitude wave line drifts almost motionlessly across the bottom of the frame.',
    animationSpec: 'waves engine · 1 layer · amplitude 8px · speed 1.5 · solid fill · muted blue-gray palette.',
    thumbnailConcept: 'A dark slate tile with a single faint, nearly flat wave line near the bottom.',
    tags: ['prayer', 'stillness', 'blue', 'calm', 'minimal'],
    recommendedUsage: 'Prayer for peace/anxiety, quiet reflection slides, guided meditation moments.',
    params: { engine: 'waves', background: '#0a0e12', bandColors: ['#2b3946'], layers: 1, amplitude: 8, speed: 1.5, fill: 'solid' },
  },
  {
    id: 'prayer-soft-dust-motes',
    name: 'Soft Dust Motes',
    category: 'prayer',
    description: 'Faint off-white specks drift lazily, like dust suspended in a shaft of light through a quiet sanctuary.',
    visualBehavior: 'Sparse pale dots drift in slow loose loops with no glow or twinkle, staying subtle throughout.',
    animationSpec: 'particles engine · 24 particles · drift direction · speed 3px/s · no glow, no twinkle · off-white palette.',
    thumbnailConcept: 'A soft dark-gray tile with faint pale specks scattered thinly across it.',
    tags: ['prayer', 'dust', 'subtle', 'quiet', 'reflective'],
    recommendedUsage: 'Personal prayer/reflection slides, pre-sermon quiet moments.',
    params: { engine: 'particles', background: '#0f0f11', particleColors: ['#d8d6cf', '#c4c2ba'], count: 24, minSize: 1, maxSize: 2.5, direction: 'drift', speed: 3, glow: false, twinkle: false },
  },
  {
    id: 'prayer-midnight-aurora',
    name: 'Midnight Aurora',
    category: 'prayer',
    description: 'Deep indigo and slate ribbons move with almost no urgency, evoking a quiet night sky.',
    visualBehavior: 'Two wide, heavily blurred ribbons shift position gradually with very slow drift.',
    animationSpec: 'aurora engine · 2 ribbons · blur 55px · speed 2 · indigo/slate palette on near-black base.',
    thumbnailConcept: 'A near-black tile with a wide, soft indigo glow occupying the middle of the frame.',
    tags: ['prayer', 'night', 'indigo', 'still', 'atmospheric'],
    recommendedUsage: 'Late-evening prayer services, night-watch/vigil settings.',
    params: { engine: 'aurora', background: '#040409', ribbonColors: ['#2a2f5e', '#3d4568'], ribbons: 2, speed: 2, blurPx: 55 },
  },
  {
    id: 'prayer-gentle-fog-gradient',
    name: 'Gentle Fog Gradient',
    category: 'prayer',
    description: 'A soft gray-blue gradient shifts almost imperceptibly, like fog settling over still ground.',
    visualBehavior: 'The color field drifts extremely slowly between muted gray and blue with a fine grain texture.',
    animationSpec: 'gradient-drift engine · angle 15° · speed 0.6 cycles/min · grain on · gray/blue/white palette.',
    thumbnailConcept: 'A muted gray-blue gradient swatch with a very fine grain texture.',
    tags: ['prayer', 'fog', 'gray', 'minimal', 'calm'],
    recommendedUsage: 'General prayer backdrop when any other motion would feel like too much.',
    params: { engine: 'gradient-drift', colors: ['#2b3138', '#3a4550', '#4c5761'], angleDeg: 15, speed: 0.6, grain: true },
  },
  {
    id: 'prayer-whispering-rays',
    name: 'Whispering Rays',
    category: 'prayer',
    description: 'Faint pale rays radiate from the center of the frame, rotating so slowly the motion is felt more than seen.',
    visualBehavior: 'Very low-opacity light rays rotate around the frame\'s center at a barely perceptible pace.',
    animationSpec: 'rays engine · 8 rays · origin center · speed 0.8°/min · opacity 0.18 · pale white palette.',
    thumbnailConcept: 'A dark tile with extremely faint pale ray shapes radiating from the middle.',
    tags: ['prayer', 'rays', 'subtle', 'light', 'peace'],
    recommendedUsage: 'Extended silent prayer, healing prayer moments, communion prayer.',
    params: { engine: 'rays', background: '#08090c', rayColor: '#e7e9f0', rayCount: 8, speed: 0.8, origin: 'center', opacity: 0.18 },
  },
  {
    id: 'prayer-silent-orbit',
    name: 'Silent Orbit',
    category: 'prayer',
    description: 'Thin concentric rings hold still while a single faint point drifts slowly around them, like a quiet clock.',
    visualBehavior: 'Static thin rings with one small dot slowly circling the outermost ring.',
    animationSpec: 'geometric engine · orbits shape · density 4 · speed 0.4 · no pulse · gray lines on near-black base.',
    thumbnailConcept: 'A dark tile with a few faint concentric circles and one small bright dot on the outer ring.',
    tags: ['prayer', 'orbit', 'minimal', 'quiet', 'contemplative'],
    recommendedUsage: 'Contemplative prayer, Taizé-style services, quiet scripture meditation.',
    params: { engine: 'geometric', background: '#0a0a0c', lineColor: '#6b7078', shape: 'orbits', density: 4, speed: 0.4, pulse: false },
  },
  {
    id: 'prayer-deep-blue-drift',
    name: 'Deep Blue Drift',
    category: 'prayer',
    description: 'A near-motionless field of navy and indigo, shifting so slowly it feels like held breath.',
    visualBehavior: 'The gradient barely moves across a very long cycle, staying almost static frame to frame.',
    animationSpec: 'gradient-drift engine · angle 60° · speed 0.4 cycles/min · grain off · navy/indigo/black palette.',
    thumbnailConcept: 'A deep navy-to-black gradient swatch, nearly solid in appearance.',
    tags: ['prayer', 'navy', 'still', 'minimal', 'dark'],
    recommendedUsage: 'Confession/repentance prayer, deeply reflective moments, funeral or memorial services.',
    params: { engine: 'gradient-drift', colors: ['#050915', '#0c1530', '#02030a'], angleDeg: 60, speed: 0.4, grain: false },
  },
  {
    id: 'prayer-falling-light',
    name: 'Falling Light',
    category: 'prayer',
    description: 'Pale gold specks drift gently downward, like light falling softly through a high window.',
    visualBehavior: 'Sparse pale-gold dots fall slowly from top to bottom with a slight, slow sway.',
    animationSpec: 'particles engine · 20 particles · down direction · speed 6px/s · glow on, no twinkle · pale gold palette.',
    thumbnailConcept: 'A dark tile with a few soft pale-gold glowing dots concentrated in the upper half.',
    tags: ['prayer', 'light', 'gold', 'gentle', 'descending'],
    recommendedUsage: 'Benediction/closing prayer, moments of receiving blessing.',
    params: { engine: 'particles', background: '#0c0a06', particleColors: ['#e8cf94', '#f2e3b8'], count: 20, minSize: 2, maxSize: 4, direction: 'down', speed: 6, glow: true, twinkle: false },
  },

  // ───────────────────────────── Bible ─────────────────────────────
  {
    id: 'bible-parchment-grain',
    name: 'Parchment Grain',
    category: 'bible',
    description: 'A warm sepia-cream gradient with a fine grain texture, evoking aged parchment or scroll.',
    visualBehavior: 'The sepia-toned color field drifts very slowly, with a constant fine grain giving it a textured, tactile feel.',
    animationSpec: 'gradient-drift engine · angle 20° · speed 0.8 cycles/min · grain on · sepia/cream/tan palette.',
    thumbnailConcept: 'A warm tan-to-cream gradient swatch with a visible fine grain texture.',
    tags: ['bible', 'scripture', 'parchment', 'warm', 'timeless'],
    recommendedUsage: 'Scripture reading slides, verse-of-the-week graphics, Bible study series backgrounds.',
    params: { engine: 'gradient-drift', colors: ['#3a2c1a', '#6b4f2e', '#8a6a3f'], angleDeg: 20, speed: 0.8, grain: true },
  },
  {
    id: 'bible-desert-dusk-rays',
    name: 'Desert Dusk Rays',
    category: 'bible',
    description: 'Warm orange-red rays fall from above like the last light of a desert sunset over ancient lands.',
    visualBehavior: 'Broad warm-toned rays sweep slowly from the top of the frame, overlapping and fading.',
    animationSpec: 'rays engine · 9 rays · origin top · speed 1.5°/min · opacity 0.4 · orange/red palette.',
    thumbnailConcept: 'A dark red-brown tile with warm orange ray shapes fanning down from the top.',
    tags: ['bible', 'desert', 'sunset', 'warm', 'rays'],
    recommendedUsage: 'Old Testament narrative series, wilderness/exodus themed teaching, historical scripture context.',
    params: { engine: 'rays', background: '#1a0d08', rayColor: '#d9622f', rayCount: 9, speed: 1.5, origin: 'top', opacity: 0.4 },
  },
  {
    id: 'bible-ancient-scroll-dust',
    name: 'Ancient Scroll Dust',
    category: 'bible',
    description: 'Fine tan dust motes drift slowly, like dust rising from an ancient scroll being unrolled.',
    visualBehavior: 'Small tan/cream specks drift in loose slow loops across a dark warm-brown backdrop.',
    animationSpec: 'particles engine · 34 particles · drift direction · speed 3px/s · no glow, twinkle on · tan/cream palette.',
    thumbnailConcept: 'A dark brown tile with fine tan specks scattered evenly across it.',
    tags: ['bible', 'scroll', 'dust', 'ancient', 'subtle'],
    recommendedUsage: 'Verse-by-verse teaching series, genealogy or history-focused messages.',
    params: { engine: 'particles', background: '#120d08', particleColors: ['#c7a978', '#e0c898'], count: 34, minSize: 1, maxSize: 2.5, direction: 'drift', speed: 3, glow: false, twinkle: true },
  },
  {
    id: 'bible-olive-grove-waves',
    name: 'Olive Grove Waves',
    category: 'bible',
    description: 'Muted olive and sage wave bands move gently, like wind through an olive grove.',
    visualBehavior: 'Two soft green-toned wave bands rise and fall slowly near the bottom of the frame.',
    animationSpec: 'waves engine · 2 layers · amplitude 18px · speed 3 · gradient fill · olive/sage palette.',
    thumbnailConcept: 'A dark olive tile with two soft overlapping green wave shapes near the bottom.',
    tags: ['bible', 'olive', 'green', 'nature', 'gentle'],
    recommendedUsage: 'Parables and nature-based teaching (vine, seeds, Gethsemane), Holy Land themed series.',
    params: { engine: 'waves', background: '#0c1006', bandColors: ['#3a4a24', '#5a6e34'], layers: 2, amplitude: 18, speed: 3, fill: 'gradient' },
  },
  {
    id: 'bible-sacred-gold-aurora',
    name: 'Sacred Gold Aurora',
    category: 'bible',
    description: 'Warm gold and cream ribbons drift softly, evoking reverence and glory.',
    visualBehavior: 'Broad, softly blurred gold-toned ribbons shift position slowly, blending where they overlap.',
    animationSpec: 'aurora engine · 3 ribbons · blur 45px · speed 3 · gold/amber/cream palette on near-black base.',
    thumbnailConcept: 'A near-black tile with a wide soft gold glow occupying the upper-middle of the frame.',
    tags: ['bible', 'gold', 'glory', 'reverent', 'soft'],
    recommendedUsage: 'Revelation/glory-themed teaching, Psalms readings, worship-adjacent scripture moments.',
    params: { engine: 'aurora', background: '#0a0602', ribbonColors: ['#c99a3f', '#e8c878', '#f2e3b0'], ribbons: 3, speed: 3, blurPx: 45 },
  },
  {
    id: 'bible-stone-path-geometric',
    name: 'Stone Path Geometric',
    category: 'bible',
    description: 'A faint warm-gray hexagonal pattern drifts steadily, like light on ancient stone paving.',
    visualBehavior: 'A hex grid pattern drifts diagonally at a slow, steady pace with no pulsing.',
    animationSpec: 'geometric engine · hex shape · density 5 · speed 1 · no pulse · warm stone-gray lines.',
    thumbnailConcept: 'A dark warm-gray tile with a faint hexagonal line pattern across it.',
    tags: ['bible', 'stone', 'geometric', 'history', 'subtle'],
    recommendedUsage: 'Teaching series on foundations/temple/covenant themes, structured Bible-study visuals.',
    params: { engine: 'geometric', background: '#0f0e0c', lineColor: '#8a8378', shape: 'hex', density: 5, speed: 1, pulse: false },
  },
  {
    id: 'bible-wilderness-amber-gradient',
    name: 'Wilderness Amber Gradient',
    category: 'bible',
    description: 'A warm amber-to-brown gradient shifts slowly, like sand and sky at the edge of the wilderness.',
    visualBehavior: 'The color field drifts gently between deep brown and warm amber over about a minute.',
    animationSpec: 'gradient-drift engine · angle 25° · speed 1 cycle/min · grain on · amber/brown/gold palette.',
    thumbnailConcept: 'A warm brown-to-amber diagonal gradient swatch with light grain.',
    tags: ['bible', 'wilderness', 'amber', 'warm', 'journey'],
    recommendedUsage: 'Exodus/wilderness teaching series, journey/pilgrimage themed messages.',
    params: { engine: 'gradient-drift', colors: ['#2e1c0d', '#5c3a1a', '#8a5f2a'], angleDeg: 25, speed: 1, grain: true },
  },
  {
    id: 'bible-jerusalem-dawn',
    name: 'Jerusalem Dawn',
    category: 'bible',
    description: 'Warm gold rays rise from the top-right corner, evoking sunrise over an ancient city.',
    visualBehavior: 'Broad gold rays sweep slowly from a top-right origin point, warm and steady.',
    animationSpec: 'rays engine · 8 rays · origin top-right · speed 1.2°/min · opacity 0.38 · warm gold palette.',
    thumbnailConcept: 'A dark tile with warm gold ray shapes radiating from the top-right corner.',
    tags: ['bible', 'dawn', 'jerusalem', 'gold', 'hope'],
    recommendedUsage: 'Resurrection/Easter scripture readings, hope-themed teaching, closing benediction verses.',
    params: { engine: 'rays', background: '#160f06', rayColor: '#e0a94a', rayCount: 8, speed: 1.2, origin: 'top-right', opacity: 0.38 },
  },
  {
    id: 'bible-vellum-scanlines',
    name: 'Vellum Scanlines',
    category: 'bible',
    description: 'Faint cream diagonal lines drift slowly over a parchment-toned backdrop, like ruled vellum pages.',
    visualBehavior: 'Thin diagonal stripes drift slowly across the frame at a shallow angle.',
    animationSpec: 'scanlines engine · stripe width 14px · angle 12° · speed 8 · opacity 0.12 · cream lines on tan base.',
    thumbnailConcept: 'A warm tan tile with faint diagonal cream stripes running across it.',
    tags: ['bible', 'vellum', 'lines', 'subtle', 'texture'],
    recommendedUsage: 'Scripture memory verse slides, sermon-note-style teaching graphics.',
    params: { engine: 'scanlines', background: '#3a2c1c', lineColor: '#e8d8b8', stripeWidth: 14, angleDeg: 12, speed: 8, opacity: 0.12 },
  },

  // ───────────────────────────── Sermon ─────────────────────────────
  {
    id: 'sermon-modern-slate-grid',
    name: 'Modern Slate Grid',
    category: 'sermon',
    description: 'A faint slate-gray grid drifts almost imperceptibly, giving structure without drawing focus from the teaching.',
    visualBehavior: 'Thin gray grid lines drift very slowly, with a subtle, slow brightness pulse.',
    animationSpec: 'geometric engine · grid shape · density 4 · speed 0.6 · pulse on (subtle) · slate-gray lines.',
    thumbnailConcept: 'A dark slate tile with a faint, evenly-spaced gray grid pattern.',
    tags: ['sermon', 'modern', 'minimal', 'grid', 'clean'],
    recommendedUsage: 'Default sermon/teaching background — main points, outline slides, general preaching.',
    params: { engine: 'geometric', background: '#0d0f12', lineColor: '#3d4650', shape: 'grid', density: 4, speed: 0.6, pulse: true },
  },
  {
    id: 'sermon-clean-horizon-gradient',
    name: 'Clean Horizon Gradient',
    category: 'sermon',
    description: 'A slow charcoal-to-slate gradient with a subtle blue undertone, calm and unobtrusive.',
    visualBehavior: 'The color field shifts extremely slowly between two close, muted dark tones.',
    animationSpec: 'gradient-drift engine · angle 10° · speed 0.5 cycles/min · grain off · charcoal/slate/blue palette.',
    thumbnailConcept: 'A near-black to slate-blue gradient swatch, subtle and even.',
    tags: ['sermon', 'clean', 'minimal', 'charcoal', 'neutral'],
    recommendedUsage: 'Full-length sermon backgrounds where the message, not the visual, should carry attention.',
    params: { engine: 'gradient-drift', colors: ['#0a0c10', '#141a22', '#1c2530'], angleDeg: 10, speed: 0.5, grain: false },
  },
  {
    id: 'sermon-focus-rays',
    name: 'Focus Rays',
    category: 'sermon',
    description: 'Extremely faint white rays sweep from above at a near-imperceptible pace — presence without distraction.',
    visualBehavior: 'Very low-opacity rays rotate slowly from the top of the frame, barely visible.',
    animationSpec: 'rays engine · 6 rays · origin top · speed 0.6°/min · opacity 0.15 · white palette.',
    thumbnailConcept: 'A near-black tile with extremely faint pale ray shapes from the top edge.',
    tags: ['sermon', 'subtle', 'rays', 'focus', 'minimal'],
    recommendedUsage: 'Key-point/quote slides during a message, moments needing maximum text legibility.',
    params: { engine: 'rays', background: '#08090b', rayColor: '#e8eaf0', rayCount: 6, speed: 0.6, origin: 'top', opacity: 0.15 },
  },
  {
    id: 'sermon-minimal-particles',
    name: 'Minimal Particles',
    category: 'sermon',
    description: 'A handful of soft, dim white dots drift almost still, adding a touch of life without any glow or sparkle.',
    visualBehavior: 'Very few small pale dots drift slowly in loose loops with no glow or twinkle.',
    animationSpec: 'particles engine · 12 particles · drift direction · speed 2px/s · no glow, no twinkle · white/gray palette.',
    thumbnailConcept: 'A dark charcoal tile with a few faint pale dots scattered sparsely.',
    tags: ['sermon', 'minimal', 'subtle', 'neutral', 'clean'],
    recommendedUsage: 'Long-form teaching, verse-by-verse exposition, seminary/conference-style sessions.',
    params: { engine: 'particles', background: '#0c0d0f', particleColors: ['#8a8d92', '#c4c6ca'], count: 12, minSize: 1, maxSize: 2, direction: 'drift', speed: 2, glow: false, twinkle: false },
  },
  {
    id: 'sermon-studio-waves',
    name: 'Studio Waves',
    category: 'sermon',
    description: 'A single dark-navy wave band moves with restrained, minimal amplitude, like a calm broadcast studio backdrop.',
    visualBehavior: 'One flat, low-amplitude wave line drifts slowly across the very bottom edge.',
    animationSpec: 'waves engine · 1 layer · amplitude 6px · speed 2 · solid fill · dark navy palette.',
    thumbnailConcept: 'A near-black tile with one thin, nearly flat navy line at the very bottom.',
    tags: ['sermon', 'studio', 'minimal', 'navy', 'broadcast'],
    recommendedUsage: 'Livestream-forward services, broadcast-style teaching sets, panel/interview segments.',
    params: { engine: 'waves', background: '#06080b', bandColors: ['#101c2c'], layers: 1, amplitude: 6, speed: 2, fill: 'solid' },
  },
  {
    id: 'sermon-signal-scanlines',
    name: 'Signal Scanlines',
    category: 'sermon',
    description: 'Thin blue diagonal lines drift steadily, giving a modern, tech-forward broadcast feel.',
    visualBehavior: 'Fine diagonal stripes move at a steady, moderate pace across the frame.',
    animationSpec: 'scanlines engine · stripe width 6px · angle 18° · speed 14 · opacity 0.1 · blue lines on charcoal base.',
    thumbnailConcept: 'A dark charcoal tile with fine diagonal blue stripes running across it.',
    tags: ['sermon', 'tech', 'modern', 'lines', 'broadcast'],
    recommendedUsage: 'Tech/innovation-themed messages, modern church plants, livestream lower-third backdrops.',
    params: { engine: 'scanlines', background: '#0a0c10', lineColor: '#3a6ea8', stripeWidth: 6, angleDeg: 18, speed: 14, opacity: 0.1 },
  },
  {
    id: 'sermon-orbit-data-points',
    name: 'Orbit Data Points',
    category: 'sermon',
    description: 'Thin blue concentric rings hold steady while single points slowly orbit them, like a data visualization.',
    visualBehavior: 'Static concentric rings with a few small dots slowly circling at different rates.',
    animationSpec: 'geometric engine · orbits shape · density 5 · speed 0.5 · no pulse · blue lines on near-black base.',
    thumbnailConcept: 'A dark tile with a few faint concentric circles and small blue dots along them.',
    tags: ['sermon', 'orbit', 'data', 'modern', 'subtle'],
    recommendedUsage: 'Vision/strategy messages, series on order/purpose/design, leadership-focused teaching.',
    params: { engine: 'geometric', background: '#080a0e', lineColor: '#3d6690', shape: 'orbits', density: 5, speed: 0.5, pulse: false },
  },
  {
    id: 'sermon-deep-space-aurora',
    name: 'Deep Space Aurora',
    category: 'sermon',
    description: 'Faint indigo and blue ribbons drift subtly, wide and unobtrusive.',
    visualBehavior: 'Two broad, heavily blurred ribbons shift very slowly across a deep-blue backdrop.',
    animationSpec: 'aurora engine · 2 ribbons · blur 50px · speed 2.5 · indigo/blue palette on near-black base.',
    thumbnailConcept: 'A near-black tile with a faint wide indigo-blue glow in the upper half.',
    tags: ['sermon', 'space', 'subtle', 'blue', 'atmospheric'],
    recommendedUsage: 'Series on identity/creation/cosmos, evening services, a softer alternative to Modern Slate Grid.',
    params: { engine: 'aurora', background: '#04060c', ribbonColors: ['#1c2a5c', '#26407a'], ribbons: 2, speed: 2.5, blurPx: 50 },
  },
  {
    id: 'sermon-charcoal-drift',
    name: 'Charcoal Drift',
    category: 'sermon',
    description: 'A near-black to charcoal gradient shifts so gradually it reads as almost still — the most neutral option in the library.',
    visualBehavior: 'The color field cycles very slowly between three closely related dark neutrals.',
    animationSpec: 'gradient-drift engine · angle 0° · speed 0.3 cycles/min · grain off · near-black/charcoal/slate palette.',
    thumbnailConcept: 'A near-solid charcoal-black gradient swatch with almost no visible variation.',
    tags: ['sermon', 'neutral', 'dark', 'minimal', 'default'],
    recommendedUsage: 'The safest possible background for dense, text-heavy teaching slides.',
    params: { engine: 'gradient-drift', colors: ['#050505', '#101012', '#181a1e'], angleDeg: 0, speed: 0.3, grain: false },
  },

  // ─────────────────────────── Countdown ───────────────────────────
  {
    id: 'countdown-classic-ring',
    name: 'Classic Countdown Ring',
    category: 'countdown',
    description: 'A clean lime progress ring sweeps down as time runs out, with a large legible time readout in the center.',
    visualBehavior: 'A bright ring arcs from full circle down to nothing as the countdown proceeds, with digits ticking down in the middle.',
    animationSpec: 'countdown-ring engine · default duration 300s · lime ring/accent on obsidian track · digits on.',
    thumbnailConcept: 'A dark tile with a bright lime ring around a large "5:00" readout.',
    tags: ['countdown', 'ring', 'lime', 'timer', 'clean'],
    recommendedUsage: 'The default pre-service countdown — matches the app\'s own brand accent.',
    params: { engine: 'countdown-ring', background: '#081214', ringColor: '#B6D72F', trackColor: '#1c2a1a', accentColor: '#FFFAB1', defaultDurationSeconds: 300, showDigits: true },
  },
  {
    id: 'countdown-crimson-ring',
    name: 'Crimson Countdown Ring',
    category: 'countdown',
    description: 'A bold red progress ring for a more urgent, high-energy countdown feel.',
    visualBehavior: 'A thick red ring sweeps down against a black track, with a matching red digital readout.',
    animationSpec: 'countdown-ring engine · default duration 300s · red ring on near-black track · digits on.',
    thumbnailConcept: 'A near-black tile with a bold red ring around a large time readout.',
    tags: ['countdown', 'ring', 'red', 'timer', 'energetic'],
    recommendedUsage: 'Youth services, high-energy pre-service hype countdowns.',
    params: { engine: 'countdown-ring', background: '#0e0505', ringColor: '#e0342f', trackColor: '#2a1414', accentColor: '#ffb0a8', defaultDurationSeconds: 300, showDigits: true },
  },
  {
    id: 'countdown-golden-ring',
    name: 'Golden Countdown Ring',
    category: 'countdown',
    description: 'A warm gold progress ring against a cream-brown track — elegant and traditional.',
    visualBehavior: 'A gold ring sweeps down against a warm brown track, with a cream-toned readout.',
    animationSpec: 'countdown-ring engine · default duration 300s · gold ring on warm-brown track · digits on.',
    thumbnailConcept: 'A warm dark-brown tile with a gold ring around a cream time readout.',
    tags: ['countdown', 'ring', 'gold', 'timer', 'elegant'],
    recommendedUsage: 'Traditional/liturgical services, Christmas Eve or Easter pre-service countdowns.',
    params: { engine: 'countdown-ring', background: '#140f06', ringColor: '#d9a63e', trackColor: '#2c2213', accentColor: '#f2e3b0', defaultDurationSeconds: 300, showDigits: true },
  },
  {
    id: 'countdown-ocean-ring',
    name: 'Ocean Countdown Ring',
    category: 'countdown',
    description: 'A cool teal progress ring against a deep navy track — calm and steady.',
    visualBehavior: 'A teal ring sweeps down against a navy track, with a pale-teal readout.',
    animationSpec: 'countdown-ring engine · default duration 300s · teal ring on navy track · digits on.',
    thumbnailConcept: 'A deep navy tile with a teal ring around a pale-teal time readout.',
    tags: ['countdown', 'ring', 'teal', 'timer', 'calm'],
    recommendedUsage: 'Reflective/contemplative services, baptism or communion service countdowns.',
    params: { engine: 'countdown-ring', background: '#050d12', ringColor: '#2fb8b0', trackColor: '#12262a', accentColor: '#a8e8e0', defaultDurationSeconds: 300, showDigits: true },
  },
  {
    id: 'countdown-violet-ring',
    name: 'Violet Countdown Ring',
    category: 'countdown',
    description: 'A rich violet progress ring against a near-black track — modern and distinctive.',
    visualBehavior: 'A violet ring sweeps down against a near-black track, with a lavender readout.',
    animationSpec: 'countdown-ring engine · default duration 300s · violet ring on near-black track · digits on.',
    thumbnailConcept: 'A near-black tile with a violet ring around a lavender time readout.',
    tags: ['countdown', 'ring', 'violet', 'timer', 'modern'],
    recommendedUsage: 'Modern worship nights, prayer & worship evenings, conference-style gatherings.',
    params: { engine: 'countdown-ring', background: '#0a0710', ringColor: '#8a5cd6', trackColor: '#1c1630', accentColor: '#d8c8f2', defaultDurationSeconds: 300, showDigits: true },
  },
  {
    id: 'countdown-energy-particles',
    name: 'Countdown Energy Particles',
    category: 'countdown',
    description: 'Bright multicolor particles rise quickly with glowing trails — high-energy atmosphere for a custom countdown overlay.',
    visualBehavior: 'Many bright dots rise briskly with strong glow, more energetic and faster than any worship preset.',
    animationSpec: 'particles engine · 70 particles · up direction · speed 40px/s · glow+twinkle on · bright multicolor palette.',
    thumbnailConcept: 'A dark tile filled with bright, fast-glowing multicolor dots rising from the bottom.',
    tags: ['countdown', 'particles', 'energetic', 'bright', 'hype'],
    recommendedUsage: 'Pair with a separately-inserted countdown text/timer element for an energetic pre-service look.',
    params: { engine: 'particles', background: '#08060c', particleColors: ['#e0342f', '#2fb8a6', '#e0a13d', '#8a5cd6'], count: 70, minSize: 2, maxSize: 5, direction: 'up', speed: 40, glow: true, twinkle: true },
  },
  {
    id: 'countdown-pulse-rays',
    name: 'Countdown Pulse Rays',
    category: 'countdown',
    description: 'Bright white rays sweep quickly from the center, building anticipation.',
    visualBehavior: 'Fast-rotating bright rays sweep from the center outward, much quicker than any other rays preset.',
    animationSpec: 'rays engine · 12 rays · origin center · speed 18°/min · opacity 0.5 · white palette.',
    thumbnailConcept: 'A dark tile with bright white ray shapes radiating fast from the center.',
    tags: ['countdown', 'rays', 'energetic', 'bright', 'anticipation'],
    recommendedUsage: 'The final 60 seconds before going live — pairs well with a bold countdown number overlay.',
    params: { engine: 'rays', background: '#08090c', rayColor: '#f2f4fa', rayCount: 12, speed: 18, origin: 'center', opacity: 0.5 },
  },
  {
    id: 'countdown-grid-rush',
    name: 'Countdown Grid Rush',
    category: 'countdown',
    description: 'A bright cyan grid rushes across the frame at speed, giving a sense of momentum before service starts.',
    visualBehavior: 'A cyan grid pattern drifts quickly and pulses noticeably faster than the sermon-collection grids.',
    animationSpec: 'geometric engine · grid shape · density 8 · speed 6 · pulse on · bright cyan lines.',
    thumbnailConcept: 'A dark tile with a bright, dense cyan grid pattern.',
    tags: ['countdown', 'grid', 'energetic', 'cyan', 'momentum'],
    recommendedUsage: 'Tech-forward or youth-oriented pre-service countdowns.',
    params: { engine: 'geometric', background: '#04080a', lineColor: '#3ed6e0', shape: 'grid', density: 8, speed: 6, pulse: true },
  },
  {
    id: 'countdown-heartbeat',
    name: 'Countdown Heartbeat',
    category: 'countdown',
    description: 'Pulsing red rings and an orbiting point beat like a heartbeat, building anticipation for the final moments.',
    visualBehavior: 'Concentric rings pulse in brightness in a heartbeat-like rhythm while a bright point circles them quickly.',
    animationSpec: 'geometric engine · orbits shape · density 4 · speed 2.5 · pulse on · red lines on near-black base.',
    thumbnailConcept: 'A dark tile with a few pulsing red concentric circles and one bright orbiting dot.',
    tags: ['countdown', 'heartbeat', 'red', 'energetic', 'pulse'],
    recommendedUsage: 'The last 10–30 seconds of a countdown, right before cutting to the live service.',
    params: { engine: 'geometric', background: '#0c0505', lineColor: '#e0342f', shape: 'orbits', density: 4, speed: 2.5, pulse: true },
  },

  // ────────────────────────── Announcement ──────────────────────────
  {
    id: 'announcement-community-confetti',
    name: 'Community Confetti Drift',
    category: 'announcement',
    description: 'Small multicolor confetti-like dots drift gently, giving a celebratory, community-event feel.',
    visualBehavior: 'Small colorful dots drift diagonally at a moderate pace without any glow, like scattered confetti.',
    animationSpec: 'particles engine · 55 particles · drift direction · speed 10px/s · no glow, twinkle on · bright multicolor palette.',
    thumbnailConcept: 'A dark tile scattered with small bright dots in several different colors.',
    tags: ['announcement', 'confetti', 'colorful', 'community', 'celebration'],
    recommendedUsage: 'Sign-up drives, event promotions, baptism celebrations, new member welcomes.',
    params: { engine: 'particles', background: '#0a0810', particleColors: ['#e0342f', '#2fb8a6', '#e0a13d', '#8a5cd6', '#e06fa0'], count: 55, minSize: 2, maxSize: 5, direction: 'drift', speed: 10, glow: false, twinkle: true },
  },
  {
    id: 'announcement-celebration-rays',
    name: 'Celebration Rays',
    category: 'announcement',
    description: 'Bright warm rays sweep energetically from the top, like a spotlight moment for good news.',
    visualBehavior: 'Bold warm-toned rays rotate briskly from the top of the frame with noticeable brightness.',
    animationSpec: 'rays engine · 10 rays · origin top · speed 10°/min · opacity 0.45 · warm gold/orange palette.',
    thumbnailConcept: 'A dark tile with bright warm ray shapes fanning energetically from the top.',
    tags: ['announcement', 'celebration', 'bright', 'rays', 'spotlight'],
    recommendedUsage: 'Big announcements, milestone celebrations, ministry highlight reels.',
    params: { engine: 'rays', background: '#140c04', rayColor: '#f2a83d', rayCount: 10, speed: 10, origin: 'top', opacity: 0.45 },
  },
  {
    id: 'announcement-event-horizon-gradient',
    name: 'Event Horizon Gradient',
    category: 'announcement',
    description: 'A bright, fast-shifting teal-pink-orange gradient — bold and eye-catching for events.',
    visualBehavior: 'The color field cycles noticeably faster than any worship/prayer gradient, shifting hue every few seconds.',
    animationSpec: 'gradient-drift engine · angle 45° · speed 3 cycles/min · grain off · teal/pink/orange palette.',
    thumbnailConcept: 'A vivid diagonal gradient swatch moving between teal, pink, and orange.',
    tags: ['announcement', 'bright', 'gradient', 'event', 'bold'],
    recommendedUsage: 'Retreats, conferences, big single-event promotion slides.',
    params: { engine: 'gradient-drift', colors: ['#1a7a7a', '#c23a6e', '#d97a2e'], angleDeg: 45, speed: 3, grain: false },
  },
  {
    id: 'announcement-bright-bokeh-pop',
    name: 'Bright Bokeh Pop',
    category: 'announcement',
    description: 'Colorful glowing bokeh orbs drift and twinkle energetically, more vivid and faster than the worship bokeh preset.',
    visualBehavior: 'Larger multicolor glowing dots drift with a noticeable bounce and brighter twinkle than worship presets.',
    animationSpec: 'particles engine · 40 particles · drift direction · speed 16px/s · glow+twinkle on · bright multicolor palette.',
    thumbnailConcept: 'A dark tile with large, vivid, glowing multicolor bokeh circles.',
    tags: ['announcement', 'bokeh', 'colorful', 'bright', 'fun'],
    recommendedUsage: 'Kids/family ministry announcements, VBS promotion, fun community events.',
    params: { engine: 'particles', background: '#0a0812', particleColors: ['#e0342f', '#3ed6c8', '#f2c23d', '#8a5cd6'], count: 40, minSize: 4, maxSize: 9, direction: 'drift', speed: 16, glow: true, twinkle: true },
  },
  {
    id: 'announcement-wave-pop',
    name: 'Announcement Wave Pop',
    category: 'announcement',
    description: 'Bright coral and teal wave bands move energetically, giving announcements a fresh, modern feel.',
    visualBehavior: 'Three vivid wave bands move at a noticeably brisk pace with high contrast between layers.',
    animationSpec: 'waves engine · 3 layers · amplitude 30px · speed 10 · gradient fill · coral/teal palette.',
    thumbnailConcept: 'A dark tile with three bright overlapping coral and teal wave shapes.',
    tags: ['announcement', 'coral', 'teal', 'energetic', 'modern'],
    recommendedUsage: 'Sermon series launches, sign-up campaigns, social-media-style announcement loops.',
    params: { engine: 'waves', background: '#0a0e10', bandColors: ['#e0665a', '#2fb8a6', '#e0a13d'], layers: 3, amplitude: 30, speed: 10, fill: 'gradient' },
  },
  {
    id: 'announcement-social-grid-flash',
    name: 'Social Grid Flash',
    category: 'announcement',
    description: 'A bright pink grid pulses noticeably, giving a fun, social-media-native energy.',
    visualBehavior: 'A pink grid drifts and pulses brightness at a fast, noticeable rate.',
    animationSpec: 'geometric engine · grid shape · density 7 · speed 4 · pulse on · bright pink lines.',
    thumbnailConcept: 'A dark tile with a bright, pulsing pink grid pattern.',
    tags: ['announcement', 'grid', 'pink', 'fun', 'social'],
    recommendedUsage: 'Instagram-style announcement slides shown on screen, youth/young-adult events.',
    params: { engine: 'geometric', background: '#0c060a', lineColor: '#e06fa8', shape: 'grid', density: 7, speed: 4, pulse: true },
  },
  {
    id: 'announcement-sunrise-aurora-burst',
    name: 'Sunrise Aurora Burst',
    category: 'announcement',
    description: 'Bright orange, pink, and yellow ribbons move energetically — a bold, hopeful visual for good news.',
    visualBehavior: 'Wide, vivid ribbons shift quickly and brightly, faster than any worship/prayer aurora preset.',
    animationSpec: 'aurora engine · 4 ribbons · blur 30px · speed 8 · orange/pink/yellow palette.',
    thumbnailConcept: 'A dark tile with bright overlapping orange, pink, and yellow blurred bands.',
    tags: ['announcement', 'sunrise', 'bright', 'hopeful', 'bold'],
    recommendedUsage: 'New series launches, building campaigns, big-vision announcement moments.',
    params: { engine: 'aurora', background: '#0e0806', ribbonColors: ['#e06a2e', '#e0508a', '#f2d23d'], ribbons: 4, speed: 8, blurPx: 30 },
  },
  {
    id: 'announcement-neon-scanlines',
    name: 'Neon Scanlines',
    category: 'announcement',
    description: 'Bright cyan and magenta diagonal lines sweep quickly, giving a fun, modern, high-energy look.',
    visualBehavior: 'Fast, bright diagonal stripes alternate between cyan and magenta as they move across the frame.',
    animationSpec: 'scanlines engine · stripe width 10px · angle 22° · speed 30 · opacity 0.22 · cyan/magenta lines.',
    thumbnailConcept: 'A dark tile with bright, fast diagonal cyan and magenta stripes.',
    tags: ['announcement', 'neon', 'bright', 'fun', 'energetic'],
    recommendedUsage: 'Youth events, concerts, high-energy community nights.',
    params: { engine: 'scanlines', background: '#08060c', lineColor: '#3ed6e0', stripeWidth: 10, angleDeg: 22, speed: 30, opacity: 0.22 },
  },
  {
    id: 'announcement-welcome-home-gradient',
    name: 'Welcome Home Gradient',
    category: 'announcement',
    description: 'A warm, inviting orange-gold-cream gradient that feels like a welcome mat for guests.',
    visualBehavior: 'The color field shifts warmly and steadily between orange, gold, and cream tones.',
    animationSpec: 'gradient-drift engine · angle 30° · speed 1.8 cycles/min · grain on · orange/gold/cream palette.',
    thumbnailConcept: 'A warm orange-to-cream diagonal gradient swatch with a soft grain texture.',
    tags: ['announcement', 'welcome', 'warm', 'inviting', 'gradient'],
    recommendedUsage: 'New guest welcome slides, hospitality announcements, "we\'re glad you\'re here" moments.',
    params: { engine: 'gradient-drift', colors: ['#7a3a1a', '#c2782e', '#e8cf94'], angleDeg: 30, speed: 1.8, grain: true },
  },
];

export function getMotionPresetById(id: string): MotionPreset | undefined {
  return MOTION_PRESETS.find((m) => m.id === id);
}

export interface MotionSearchOptions {
  query?: string;
  category?: import('@/types/motion').MotionCategory | 'all';
  favoriteIds?: Set<string>;
  favoritesOnly?: boolean;
}

/** Pure client-side filter over the static catalog — no server round-trip needed for built-in content. */
export function searchMotionPresets({ query, category, favoriteIds, favoritesOnly }: MotionSearchOptions): MotionPreset[] {
  const q = (query ?? '').trim().toLowerCase();
  return MOTION_PRESETS.filter((preset) => {
    if (category && category !== 'all' && preset.category !== category) return false;
    if (favoritesOnly && !favoriteIds?.has(preset.id)) return false;
    if (!q) return true;
    return (
      preset.name.toLowerCase().includes(q) ||
      preset.description.toLowerCase().includes(q) ||
      preset.tags.some((tag) => tag.toLowerCase().includes(q))
    );
  });
}
