import type { StaticCanvas } from 'fabric';
import type { SlideCanvasData } from '@/types';
import { applyImageBackground, clearBackgroundForVideo } from '@/lib/fabricObjects';
import { getMediaInfoById } from '@/lib/mediaStorage';
import { getMotionPresetById } from '@/lib/motionLibrary';
import type { MotionPreset } from '@/types/motion';

export interface RenderSlideResult {
  /** Set when the slide's background is a video — the caller renders it as a real <video> element behind the canvas. */
  videoBackgroundUrl: string | null;
  /** Set when the slide's background is a built-in Motion Background Library preset — the caller renders it via <MotionBackgroundPlayer> behind the canvas. */
  motionBackground: MotionPreset | null;
}

/**
 * Loads slide JSON onto a canvas and resolves a background that was set via
 * `meta.backgroundMediaId` without a live-canvas-serialized `backgroundImage`
 * (i.e. slides generated by Songs/Bible/Media, or any media background
 * picked in the editor). Shared by the interactive editor (EditorWorkspace)
 * and the read-only Present-mode renderer (SlideCanvasRenderer) so the two
 * never render a slide differently from each other.
 *
 * Video backgrounds are NOT composited into the Fabric canvas (that would
 * need a continuous per-frame render loop bolted onto a system that only
 * re-renders on demand). Instead the canvas background is left transparent
 * and the caller stacks a real <video> element behind it — the browser's
 * native video decoding handles the animation for free.
 */
export async function resolveAndRenderSlide(canvas: StaticCanvas, content: SlideCanvasData): Promise<RenderSlideResult> {
  await canvas.loadFromJSON(content);

  // A built-in Motion Background Library preset — no network lookup at
  // all, just resolve the id against the bundled catalog.
  const motionId = content.meta?.backgroundMotionId ?? null;
  if (motionId && !canvas.backgroundImage) {
    const preset = getMotionPresetById(motionId);
    if (preset) {
      clearBackgroundForVideo(canvas); // same "transparent canvas, something else paints behind it" treatment as video
      return { videoBackgroundUrl: null, motionBackground: preset };
    }
  }

  // A pasted external video URL (not an uploaded Media item) takes priority
  // — it needs no Supabase lookup, just point a <video> at it directly.
  const embedUrl = content.meta?.backgroundVideoEmbedUrl ?? null;
  if (embedUrl && !canvas.backgroundImage) {
    clearBackgroundForVideo(canvas);
    return { videoBackgroundUrl: embedUrl, motionBackground: null };
  }

  const bgMediaId = content.meta?.backgroundMediaId ?? null;
  if (bgMediaId && !canvas.backgroundImage) {
    const info = await getMediaInfoById(bgMediaId);
    if (info?.type === 'video') {
      clearBackgroundForVideo(canvas);
      return { videoBackgroundUrl: info.url, motionBackground: null };
    }
    if (info?.url) {
      await applyImageBackground(canvas, info.url);
    }
  }

  return { videoBackgroundUrl: null, motionBackground: null };
}
