import type { StaticCanvas } from 'fabric';
import type { SlideCanvasData } from '@/types';
import { applyImageBackground } from '@/lib/fabricObjects';
import { getMediaInfoById } from '@/lib/mediaStorage';

export interface RenderSlideResult {
  /** Set when the slide's background is a video — the caller renders it as a real <video> element behind the canvas. */
  videoBackgroundUrl: string | null;
}

/**
 * Loads slide JSON onto a canvas and resolves a background that was set via
 * `meta.backgroundMediaId` without a live-canvas-serialized `backgroundImage`
 * (i.e. slides generated by Songs/Bible/Media, or any media background
 * picked in the editor). Shared by the interactive editor (EditorWorkspace)
 * and the read-only Present-mode renderer (SlideCanvasRenderer) so the two
 * never render a slide differently from each other.
 *
 * Video backgrounds are NOT composited into the Fabric canvas (that would
 * need a continuous per-frame render loop bolted onto a system that only
 * re-renders on demand). Instead the canvas background is left transparent
 * and the caller stacks a real <video> element behind it — the browser's
 * native video decoding handles the animation for free.
 */
export async function resolveAndRenderSlide(canvas: StaticCanvas, content: SlideCanvasData): Promise<RenderSlideResult> {
  await canvas.loadFromJSON(content);

  // A pasted external video URL (not an uploaded Media item) takes priority
  // — it needs no Supabase lookup, just point a <video> at it directly.
  const embedUrl = content.meta?.backgroundVideoEmbedUrl ?? null;
  if (embedUrl && !canvas.backgroundImage) {
    canvas.backgroundColor = 'transparent';
    canvas.requestRenderAll();
    return { videoBackgroundUrl: embedUrl };
  }

  const bgMediaId = content.meta?.backgroundMediaId ?? null;
  if (bgMediaId && !canvas.backgroundImage) {
    const info = await getMediaInfoById(bgMediaId);
    if (info?.type === 'video') {
      canvas.backgroundColor = 'transparent';
      canvas.requestRenderAll();
      return { videoBackgroundUrl: info.url };
    }
    if (info?.url) {
      await applyImageBackground(canvas, info.url);
    }
  }

  return { videoBackgroundUrl: null };
}
