import type { SlideCanvasData } from '@/types';
import {
  DEFAULT_SLIDE_BACKGROUND_COLOR,
  DEFAULT_TEXT_PROPS,
  SLIDE_HEIGHT,
  SLIDE_WIDTH,
} from '@/lib/editorConstants';

/**
 * Pure builders for `slides.content` — no live Fabric.js canvas required.
 *
 * These produce plain objects in Fabric's own `canvas.toJSON()` shape, so
 * slides generated by Songs/Bible/Media open in the editor fully editable
 * from the moment they're created, rather than as some placeholder the
 * editor has to specially interpret. Fabric's `loadFromJSON`/`fromObject`
 * merge a plain object with each object type's class defaults, so only the
 * properties that matter for a given object need to be specified here —
 * missing fields (scaleX/scaleY/angle/opacity/etc.) fall back to Fabric's
 * own sensible defaults.
 *
 * Kept in sync with src/lib/fabricObjects.ts, which performs the equivalent
 * operations against a *live* canvas instance inside the editor — both
 * import DEFAULT_TEXT_PROPS from editorConstants.ts so a hand-added text
 * box and a generated one look identical.
 */

let objectIdCounter = 0;

function nextObjectId(): string {
  objectIdCounter += 1;
  return `obj-${Date.now()}-${objectIdCounter}`;
}

interface TextSlideOptions {
  fontFamily?: string;
  fontSize?: number;
  fill?: string;
  textAlign?: 'left' | 'center' | 'right';
  backgroundColor?: string;
  /** A built-in Motion Background Library preset id (src/lib/motionLibrary.ts) to use as this slide's background instead of a solid color. */
  backgroundMotionId?: string | null;
  /** createVerseSlideContent only — overrides the reference caption's size instead of the default 0.4x the verse text's fontSize. */
  captionFontSize?: number;
}

/**
 * A single centered text box on an otherwise blank slide — used by Songs
 * (one section per slide) and Bible (one verse per slide).
 */
export function createTextSlideContent(text: string, options: TextSlideOptions = {}): SlideCanvasData {
  const left = (SLIDE_WIDTH - DEFAULT_TEXT_PROPS.width) / 2;

  return {
    version: '6.9.1',
    objects: [
      {
        type: 'Textbox',
        id: nextObjectId(),
        text,
        left,
        top: SLIDE_HEIGHT / 2 - 150,
        width: DEFAULT_TEXT_PROPS.width,
        fontFamily: options.fontFamily ?? DEFAULT_TEXT_PROPS.fontFamily,
        fontSize: options.fontSize ?? DEFAULT_TEXT_PROPS.fontSize,
        fill: options.fill ?? DEFAULT_TEXT_PROPS.fill,
        textAlign: options.textAlign ?? DEFAULT_TEXT_PROPS.textAlign,
      },
    ],
    background: options.backgroundColor ?? DEFAULT_SLIDE_BACKGROUND_COLOR,
    meta: { schemaVersion: 1, backgroundMediaId: null, backgroundMotionId: options.backgroundMotionId ?? null },
  };
}

/**
 * A verse text box plus a smaller reference caption (e.g. "Genesis 1:27")
 * beneath it — used by Bible so the book/chapter/verse actually appears on
 * the projected/stage output, not just as the slide's internal title (which
 * is never itself painted onto the canvas).
 */
export function createVerseSlideContent(reference: string, text: string, options: TextSlideOptions = {}): SlideCanvasData {
  const left = (SLIDE_WIDTH - DEFAULT_TEXT_PROPS.width) / 2;
  const fontSize = options.fontSize ?? DEFAULT_TEXT_PROPS.fontSize;

  return {
    version: '6.9.1',
    objects: [
      {
        type: 'Textbox',
        id: nextObjectId(),
        text,
        left,
        top: SLIDE_HEIGHT / 2 - 180,
        width: DEFAULT_TEXT_PROPS.width,
        fontFamily: options.fontFamily ?? DEFAULT_TEXT_PROPS.fontFamily,
        fontSize,
        fill: options.fill ?? DEFAULT_TEXT_PROPS.fill,
        textAlign: options.textAlign ?? DEFAULT_TEXT_PROPS.textAlign,
      },
      {
        type: 'Textbox',
        id: nextObjectId(),
        text: reference,
        left,
        top: SLIDE_HEIGHT - 170,
        width: DEFAULT_TEXT_PROPS.width,
        fontFamily: options.fontFamily ?? DEFAULT_TEXT_PROPS.fontFamily,
        fontSize: options.captionFontSize ?? Math.round(fontSize * 0.4),
        fontStyle: 'italic',
        fill: options.fill ?? DEFAULT_TEXT_PROPS.fill,
        textAlign: 'center',
      },
    ],
    background: options.backgroundColor ?? DEFAULT_SLIDE_BACKGROUND_COLOR,
    meta: { schemaVersion: 1, backgroundMediaId: null, backgroundMotionId: options.backgroundMotionId ?? null },
  };
}

/**
 * Splits lyrics text into slide-sized chunks (e.g. 4 lines each) instead of
 * one whole verse/chorus per slide — matches the "auto-split long lyrics"
 * behavior of tools like WorshipTools' Loop Connect. Blank lines are
 * dropped; a chunk with no non-blank lines is omitted entirely.
 */
export function splitTextIntoChunks(text: string, linesPerChunk: number): string[] {
  const lines = text.split('\n').map((l) => l.trim());
  const nonEmptyLines = lines.filter((l) => l.length > 0);
  if (nonEmptyLines.length === 0) return [];

  const safeChunkSize = Math.max(1, Math.floor(linesPerChunk) || 1);
  const chunks: string[] = [];
  for (let i = 0; i < nonEmptyLines.length; i += safeChunkSize) {
    chunks.push(nonEmptyLines.slice(i, i + safeChunkSize).join('\n'));
  }
  return chunks;
}

/**
 * A blank slide whose background is a media library image or video. No
 * canvas objects — the editor/Present-mode renderer resolves
 * `meta.backgroundMediaId` (and the corresponding `slides.background_id`
 * FK) into a signed URL and applies it as a background when the slide is
 * loaded. Type-agnostic — the actual image-vs-video handling happens at
 * render time via a fresh lookup of the media row's type.
 */
export function createMediaBackgroundSlideContent(mediaId: string): SlideCanvasData {
  return {
    version: '6.9.1',
    objects: [],
    background: DEFAULT_SLIDE_BACKGROUND_COLOR,
    meta: { schemaVersion: 1, backgroundMediaId: mediaId },
  };
}

/** A fully blank slide — used when creating a new presentation/slide with no content yet. */
export function createBlankSlideContent(): SlideCanvasData {
  return {
    version: '6.9.1',
    objects: [],
    background: DEFAULT_SLIDE_BACKGROUND_COLOR,
    meta: { schemaVersion: 1, backgroundMediaId: null },
  };
}

/**
 * True if a slide has no visible objects and no background image/media/
 * embed/motion/custom color — i.e. there is genuinely nothing to render, so
 * callers can skip loadFromJSON entirely and just paint the default
 * background. A slide with only a custom solid-color background (no
 * objects) is NOT empty — it must still go through resolveAndRenderSlide,
 * or its chosen color would be silently overwritten with the default on
 * every load/switch/present. Same reasoning applies to a motion-only
 * background — miss it here and a slide that's "just a Motion Library
 * preset behind some later-added text" would render as a plain default
 * background instead, every time it's loaded/switched/presented.
 */
export function isEmptySlideContent(content: SlideCanvasData | null | undefined): boolean {
  if (!content) return true;
  const objects = Array.isArray(content.objects) ? content.objects : [];
  const hasCustomBackgroundColor =
    typeof content.background === 'string' && content.background !== DEFAULT_SLIDE_BACKGROUND_COLOR;
  return (
    objects.length === 0 &&
    !content.meta?.backgroundMediaId &&
    !content.meta?.backgroundVideoEmbedUrl &&
    !content.meta?.backgroundMotionId &&
    !hasCustomBackgroundColor
  );
}
