import type { SlideCanvasData } from '@/types';
import {
  DEFAULT_SLIDE_BACKGROUND_COLOR,
  DEFAULT_TEXT_PROPS,
  SLIDE_HEIGHT,
  SLIDE_WIDTH,
} from '@/lib/editorConstants';

/**
 * Pure builders for `slides.content` — no live Fabric.js canvas required.
 *
 * These produce plain objects in Fabric's own `canvas.toJSON()` shape, so
 * slides generated by Songs/Bible/Media open in the editor fully editable
 * from the moment they're created, rather than as some placeholder the
 * editor has to specially interpret. Fabric's `loadFromJSON`/`fromObject`
 * merge a plain object with each object type's class defaults, so only the
 * properties that matter for a given object need to be specified here —
 * missing fields (scaleX/scaleY/angle/opacity/etc.) fall back to Fabric's
 * own sensible defaults.
 *
 * Kept in sync with src/lib/fabricObjects.ts, which performs the equivalent
 * operations against a *live* canvas instance inside the editor — both
 * import DEFAULT_TEXT_PROPS from editorConstants.ts so a hand-added text
 * box and a generated one look identical.
 */

let objectIdCounter = 0;

function nextObjectId(): string {
  objectIdCounter += 1;
  return `obj-${Date.now()}-${objectIdCounter}`;
}

interface TextSlideOptions {
  fontFamily?: string;
  fontSize?: number;
  fill?: string;
  textAlign?: 'left' | 'center' | 'right';
  backgroundColor?: string;
}

/**
 * A single centered text box on an otherwise blank slide — used by Songs
 * (one section per slide) and Bible (one verse per slide).
 */
export function createTextSlideContent(text: string, options: TextSlideOptions = {}): SlideCanvasData {
  const left = (SLIDE_WIDTH - DEFAULT_TEXT_PROPS.width) / 2;

  return {
    version: '6.9.1',
    objects: [
      {
        type: 'Textbox',
        id: nextObjectId(),
        text,
        left,
        top: SLIDE_HEIGHT / 2 - 150,
        width: DEFAULT_TEXT_PROPS.width,
        fontFamily: options.fontFamily ?? DEFAULT_TEXT_PROPS.fontFamily,
        fontSize: options.fontSize ?? DEFAULT_TEXT_PROPS.fontSize,
        fill: options.fill ?? DEFAULT_TEXT_PROPS.fill,
        textAlign: options.textAlign ?? DEFAULT_TEXT_PROPS.textAlign,
      },
    ],
    background: options.backgroundColor ?? DEFAULT_SLIDE_BACKGROUND_COLOR,
    meta: { schemaVersion: 1, backgroundMediaId: null },
  };
}

/**
 * A blank slide whose background is a media library image. No canvas
 * objects — the editor resolves `meta.backgroundMediaId` (and the
 * corresponding `slides.background_id` FK) into a signed URL and applies it
 * as `canvas.backgroundImage` when the slide is loaded.
 */
export function createImageBackgroundSlideContent(mediaId: string): SlideCanvasData {
  return {
    version: '6.9.1',
    objects: [],
    background: DEFAULT_SLIDE_BACKGROUND_COLOR,
    meta: { schemaVersion: 1, backgroundMediaId: mediaId },
  };
}

/** A fully blank slide — used when creating a new presentation/slide with no content yet. */
export function createBlankSlideContent(): SlideCanvasData {
  return {
    version: '6.9.1',
    objects: [],
    background: DEFAULT_SLIDE_BACKGROUND_COLOR,
    meta: { schemaVersion: 1, backgroundMediaId: null },
  };
}

/** True if a slide's content has no visible objects and no background image/media. */
export function isEmptySlideContent(content: SlideCanvasData | null | undefined): boolean {
  if (!content) return true;
  const objects = Array.isArray(content.objects) ? content.objects : [];
  return objects.length === 0 && !content.meta?.backgroundMediaId;
}
